baseURL = "https://fordt.org.ar/"
languageCode = "es"
defaultContentLanguage = "es"
title = "Club del Ford T de Argentina"
theme = "mainroad"

[minify]
  disableJS = true

[params]
  description = "Primer Club del Ford T de Argentina"
  copyright = "Club del Ford T de Argentina"
  opengraph = true
  readmore = true
  authorbox = false
  pager = true
  post_meta = ["date", "categories"]
  dateformat = "2 January, 2006"
  highlightColor = "#8B0000"
  customCSS = ["css/custom.css"]
  customJS = ["js/pub-viewer.js"]
  mainSections = ["posts"]

[params.logo]
  title = "Primer Club Ford T Argentina"
  subtitle = "Desde 1996 reunidos bajo la misma pasión"
  image = "/images/logo-club.png"

[params.sidebar]
  home = false
  list = false
  single = false
  widgets = ["search", "recent", "categories"]

[params.widgets]
  recent_num = 5
  categories_counter = false

[[menu.main]]
  name = "El Club"
  url = "/el-club/"
  weight = 1
[[menu.main]]
  name = "Socios"
  url = "/socios/"
  weight = 2
[[menu.main]]
  name = "Técnica"
  url = "/tecnica/"
  weight = 3
[[menu.main]]
  name = "Encuentros"
  url = "/encuentros/"
  weight = 4
[[menu.main]]
  name = "Actividades"
  url = "/actividades/"
  weight = 5

[[menu.footer]]
  name = "Contacto"
  url = "/contacto/"
  weight = 1

[markup.goldmark.renderer]
  unsafe = true
